/* eslint-disable tailwindcss/no-custom-classname */
import './globals.css';

import { Inter } from 'next/font/google';

import Navigation from './view/Shared/Navigation/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col">
          <Navigation />
          <main className="container mx-auto max-w-screen-xl flex-1 px-5 py-10">{children}</main>
          <footer className="border-t py-5">
            <div className="text-grey-500 text-center text-sm">
              Copyright @ All rigths reserved | Nakagome
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
